### ISSUE TITLE
no logs in accessLog file

### ISSUE THREAD

**Issue by SpontaneousOverthrow** [emeraldpay/dshackle#102]
dshackle build from master running in docker.
dshackle config:
```
version: v1
port: 2449
tls:
  enabled: false

cache:
  redis:
    enabled: false

proxy:
  host: 0.0.0.0
  port: 8545
  routes:
    - id: mainnet
      blockchain: ethereum

cluster:
  upstreams:

    - id: mainnet-eth-node-02
      chain: ethereum
      labels:
              fullnode: true
      connection:
        ethereum:
          rpc:
                      url: "http://10.0.10.2:28545"
          ws:
                      url: "ws://10.0.10.2:28545"

accessLog:
  enabled: true
```
Log file persist in docker container but it's empty:
```/access_log.jsonl```

There are number of request to dshackle node:
```
dshackle_request_grpc_request_total{chain="NA",type="describe",} 0.0
dshackle_request_grpc_request_total{chain="NA",type="subscribeStatus",} 0.0
dshackle_request_jsonrpc_request_total{chain="RINKEBY",} 266.0
dshackle_request_jsonrpc_request_total{chain="ETH",} 630.0
```
