### ISSUE TITLE
Option to disable all default methods

### ISSUE THREAD

**Issue by splix** [emeraldpay/dshackle#120]
Allow config like:

```
options:
  disable-validation: true
methods:
  disable-default: true
  enabled:
    - name: my_customMethod
```

Which disables all standard methods: https://github.com/emeraldpay/dshackle/blob/master/docs/04-upstream-config.adoc
and routes only `my_customMethod` to that upstream
