### ISSUE TITLE
WebSocket Proxy Returns 404

### ISSUE THREAD

**Issue by willrnch** [emeraldpay/dshackle#126]
I use version `0.10.1` with the following config:

```yml
version: v1
port: 2449
tls:
  enabled: false

proxy:
  host: 0.0.0.0
  port: 8545
  websocket: true
  routes:
    - id: eth
      blockchain: ethereum

cluster:
  upstreams:
    - id: infura-eth
      chain: ethereum
      connection:
        ethereum:
          rpc:
            url: "https://mainnet.infura.io/v3/********************************"
          ws:
            url: "wss://mainnet.infura.io/ws/v3/********************************"
```

The HTTP endpoint works fine:

```
curl http://127.0.0.1:8545/eth -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}'
{"jsonrpc":"2.0","id":83,"result":"0xd09ef0"}
```

 However, the websocket always returns a 404:

```
./websocat_linux64 ws://127.0.0.1:8545/eth
websocat: WebSocketError: Received unexpected status code (404 Not Found)
websocat: error running
```
