### ISSUE TITLE
Enable/disable methods by mask

### ISSUE THREAD

**Issue by splix** [emeraldpay/dshackle#129]
Instead of:

```
methods:
    enabled:
      - name: trace_call
      - name: trace_replayTransaction
      - ....
```

allow:

```
methods:
    enabled:
      - name: trace_*
```
