### ISSUE TITLE
Unable to connect grafana+prometeus

### ISSUE THREAD

**Issue by nforced** [emeraldpay/dshackle#154]
Can somebody please share how to connect the Grafana dashboard?

I've imported https://raw.githubusercontent.com/emeraldpay/dshackle/master/dashboard/dshackle.json and tried to add Prometeus data source to Grafana Enterprice with no luck.
```
monitoring:
  enabled: true
  jvm: false
  extended: false
  prometheus:
    enabled: true
    bind: 192.168.0.1
    port: 8000
    path: /status/prometheus

docker run -p 2449:2449 -p 8545:8545 -p 8000:8000 -v /etc/dshackle:/etc/dshackle emeraldpay/dshackle:0.12
...
MonitoringSetup | Run Prometheus metrics on 127.0.0.1:8000/status/prometheus
```

When I try to "save and test" (doing https://grafana-host/api/ds/query) I get different errors like so:

`Error reading Prometheus: bad_response: readObjectStart: expect { or n, but found #, error found in #1 byte of ...|# HELP dsha|..., bigger context ...|# HELP dshackle_upstream_ws_fail_total Number of fa|...
`

`Error reading Prometheus: bad_response: readObjectStart: expect { or n, but found #, error found in #1 byte of ...|# HELP dsha|..., bigger context ...|# HELP dshackle_request_grpc_request_total # TYPE|...`

Still I can do curl http://127.0.0.1:8000/status/prometheus and get list of different metrics where I see lines starting with comments which to me seem related to the above response errors
```
dshackle_upstream_ws_conn_seconds_count{chain="ETH",upstream="node1",} 71.0
dshackle_upstream_ws_conn_seconds_sum{chain="ETH",upstream="node1",} 0.956933337
# HELP dshackle_upstream_ws_conn_seconds_max Request time through a WebSocket JSON RPC connection
# TYPE dshackle_upstream_ws_conn_seconds_max gauge
dshackle_upstream_ws_conn_seconds_max{chain="ETH",upstream="node2",} 0.375663177
dshackle_upstream_ws_conn_seconds_max{chain="ETH",upstream="node1",} 0.316129182
# HELP dshackle_upstreams_lag
# TYPE dshackle_upstreams_lag gauge
dshackle_upstreams_lag{chain="ETH",upstream="node2",} 1.0
dshackle_upstreams_lag{chain="ETH",upstream="node1",} 0.0
# HELP dshackle_upstreams_availability
# TYPE dshackle_upstreams_availability gauge
```

Am I doing something wrong here?
