### ISSUE TITLE
Mixed signals

### ISSUE THREAD

**Issue by austin-lambertajollylife** [emeraldpay/dshackle#167]
I am trying to get my first dshackle instance up and I am getting mixed signals if the node is actually working. 

I deployed a dshackle instance. The logs imply that the container is grabbing new blocks every few seconds. 

Curl gives us back a valid response. 

Metamask joins to the network successfully. (although there is some UI weirdness) My friend can't seem to join his metamask.

Geth on my side says `Fatal: Failed to start the JavaScript console: api modules: The method rpc_modules does not exist/is not available` . The command I used is geth attach https://<my.url>:8545 --exec "eth.syncing.highestBlock - eth.syncing.currentBlock"

etherflow throws an error saying Error: Invalid JSON RPC response: ""

Here is my config:

```
host: 0.0.0.0
port: 2449
tls:
  enabled: true
  server:
    certificate: fullchain.pem
    key: privkey.pem

cache:
  redis:
    enabled: false
    host: redis

proxy:
  host: 0.0.0.0
  port: 8545
  tls:
    enabled: true
    server:
      certificate: fullchain.pem
      key: privkey.pem
  routes:
    - id: eth
      blockchain: ethereum
    - id: matic
      blockchain: matic

accessLog:
  enabled: true
  filename: /var/log/dshackle/

monitoring:
  enabled: true
  jvm: false
  extended: false
  prometheus:
    enabled: true
    bind: 127.0.0.1
    port: 8000
    path: /status/prometheus

health:
  port: 8082 # (1)
  host: 127.0.0.1 # (2)
  path: /health # (3)
  blockchains: # (4)
    - chain: ethereum # (5)
      min-available: 2 # (6)
    - chain: bitcoin
      min-available: 1
    - chain: polygon
      min-available: 1

cluster:
#  include: "upstreams.yaml"
  defaults:
    - chains:
        - ethereum
      options:
        min-peers: 10
#    - chains:
#        - kovan
#      options:
#        min-peers: 2



  upstreams:
    - id: polygon
      chain: matic
      connection:
        ethereum:
          rpc:
            url: "https://polygon-rpc.com"
#          ws:
#            url: "wss://polygon-rpc.com"


    - id: infura-eth
      chain: ethereum
      connection:
        ethereum:
          rpc:
            url: "https://mainnet.infura.io/v3/<my_key>"
          ws:
            url: "wss://mainnet.infura.io/ws/v3/<my_key>"

    - id: infura-eth-node-6
      chain: ethereum
      connection:
        ethereum:
          rpc:
            url: "https://mainnet.infura.io/v3/<my_key>"
          ws:
            url: "wss://mainnet.infura.io/ws/v3/<my_key>"

    - id: infura-mainnet
      chain: ethereum
      connection:
        ethereum:
          rpc:
            url: "https://mainnet.infura.io/v3/<my_key>"
          ws:
            url: "wss://mainnet.infura.io/ws/v3/<my_key>"
```
