### ISSUE TITLE
Invalid Upstream = OK

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#176]
In the current release of Dshackle if I add an invalid upstream such as:

```
    - id: infura
      chain: ethereum
      role: secondary
      priority: 90
      options:
        disable-validation: true
      connection:
        ethereum:
          rpc:
            url: "https://mainnet.infura.io/v3/"
```

(notice it's missing an API key)

Dshackle just reports it as "OK" and shows no indication that there's anything wrong with the configured upstream.
