### ISSUE TITLE
A way to reduce amount of sync calls?

### ISSUE THREAD

**Issue by PDVJAM** [emeraldpay/dshackle#178]
Hey. Recently we have added a new upstream - Cloudflare eth gateway, which doesn't have WebSockets support. Upstream was configured as a fallback, and we didn't even use it. Nevertheless, 941,536 requests were made to this endpoint during the month. As I understand it, these were only requests for getting the status / current block.
Why so much? Is this expected? Is there a way to reduce the number of these kind of requests?

**Comment by splix** [comment]
How many instances of Dshackle do you have? 

I mean, if Dshackle makes a check for every block to ensure that the upstream is good, then with a twelve second block time it's roughly 220K requests a months per instance.

**Comment by PDVJAM** [comment]
> How many instances of Dshackle do you have?
> 
> I mean, if Dshackle makes a check for every block to ensure that the upstream is good, then with a twelve second block time it's roughly 220K requests a months per instance.

2 pods (deployed to k8s).

**Comment by MysticRyuujin** [comment]
You can now tune almost all of this in the latest version, e.g.:

```yaml
      options:
        disable-validation: false
        validation-interval: 60
        validate-peers: false
        validate-syncing: true
```

https://github.com/emeraldpay/dshackle/blob/master/docs/reference-configuration.adoc#general-upstream-options
