### ISSUE TITLE
websocket returns binary blobs rather than text

### ISSUE THREAD

**Issue by nibty** [emeraldpay/dshackle#180]
I'm having issues using the Websocket provider from the ethers.js library in the browser. It seems Dshackle is returning binary blobs, which is not easily supported by browsers. Can dshackle be configured to return JSON as plain text?

> My dshackle config
```
version: v1

host: 0.0.0.0
port: 2449

proxy:
  host: 0.0.0.0
  port: 8547
  websocket: true
  tls:
    enabled: false
  routes:
    - id: eth
      blockchain: goerli

monitoring:
  enabled: true
  jvm: false
  extended: true
  prometheus:
    enabled: true
    bind: 0.0.0.0

cluster:
  upstreams:
    - id: our-node
      role: primary
      chain: goerli
      priority: 100
      connection:
        ethereum:
          rpc:
            url: "http://127.0.0.1:8545"
          ws:
            url: "http://127.0.0.1:8546"

    - id: infura-eth
      chain: goerli
      priority: 50
      role: fallback
      connection:
        ethereum:
          rpc:
            url: "https://goerli.infura.io/v3/${INFURA_USER}"
          ws:
            url: "wss://goerli.infura.io/ws/v3/${INFURA_USER}"
      labels:
        provider: infura
```

> example webpage showing connects work directly to geth but fail to dshackle
```
<html>
<script src="https://cdn.ethers.io/lib/ethers-5.2.umd.min.js"
        type="application/javascript">
</script>

<script type="application/javascript">
    // Works from geth
    let provider = new ethers.providers.WebSocketProvider("ws://127.0.0.1:8546");
    provider.getBlockNumber().then((blockNumber) => {
        console.log("from geth", blockNumber);
    });

    // fails from dshackle
    provider = new ethers.providers.WebSocketProvider("ws://127.0.0.1:8547/eth");
    provider.getBlockNumber().then((blockNumber) => {
        console.log("from dshackle", blockNumber);
    });
</script>

</html>
```

<img width="616" alt="Screen Shot 2022-09-21 at 1 54 55 PM" src="https://user-images.githubusercontent.com/2287963/191610368-1dd4eccc-5692-4794-a780-e5b12807b171.png">

<img width="712" alt="Screen Shot 2022-09-21 at 1 55 11 PM" src="https://user-images.githubusercontent.com/2287963/191610322-6c8c0488-3dc0-4bfd-8d63-64737b5cac93.png">
