### ISSUE TITLE
validation interval doesnt work?

### ISSUE THREAD

**Issue by opsjet-intuser** [emeraldpay/dshackle#220]
Hey!
I have such config:
```
      - id: infura
        chain: ethereum
        role: primary
        priority: 10
        options:
          disable-validation: true
          validation-interval: 60
        connection:
          ethereum:
            rpc:
              url: "https://mainnet.infura.io/v3/${INFURA_KEY}"
            ws:
              url: "wss://mainnet.infura.io/ws/v3/${INFURA_KEY}"
```

As I understand, it should check upstream once per minute. But in my Infura dashboard, I see 75 requests per 15 minutes, which means 5 per minute. There are no other requests to this endpoint, and no one using it.
Please, help me understand what is wrong.
