### ISSUE TITLE
weak upstream after some time

### ISSUE THREAD

**Issue by PDVJAM** [emeraldpay/dshackle#221]
So, we have a 0.13.1 version running, an Infura key, and an upstream configured. It works some time - this can be days - but then we see in Grafana that this upstream is weak.
In the docker logs, we see just something like that
```2023-04-01 15:48:34.440 | INFO  |          Multistream | State of ETH: height=16334409, status=[OK/1,SYNCING/1], lag=[0, 8078529], weak=[infura]```

But on the Infura dashboard, we still see requests, [screenshot1](https://ibb.co/PGqsRMr), [screenshot2](https://ibb.co/3mr75HV).
If we change the Infura's key for another one - it will work for some time until I see the same 'weak' behavior. But if after that we
change key to the previous one, it will work again.

What does weak actually mean? And what can be the root cause of such a thing?

**Comment by splix** [comment]
For a some reason Dshackle decided that Infura in SYNCING state and never recovered. Hard to say what was a cause; probably that a health check returned some unexpected response. But a simple restart should help.

In general, I would suggest to disable validation for upstream like Infura. I.e., set `disable-validation: true` in [config](https://github.com/emeraldpay/dshackle/blob/master/docs/reference-configuration.adoc#upstream-json). Because Infura is multiple upstream behind single url, so you cannot really validate it, also they supposed to do it on their side.

Second option is to use [Health Checks](https://github.com/emeraldpay/dshackle/blob/master/docs/reference-configuration.adoc#health) and restart Dshackle if it doesn't have enough working upstreams

**Comment by PDVJAM** [comment]
> For a some reason Dshackle decided that Infura in SYNCING state and never recovered. Hard to say what was a cause; probably that a health check returned some unexpected response. But a simple restart should help.
> 
> In general, I would suggest to disable validation for upstream like Infura. I.e., set `disable-validation: true` in [config](https://github.com/emeraldpay/dshackle/blob/master/docs/reference-configuration.adoc#upstream-json). Because Infura is multiple upstream behind single url, so you cannot really validate it, also they supposed to do it on their side.
> 
> Second option is to use [Health Checks](https://github.com/emeraldpay/dshackle/blob/master/docs/reference-configuration.adoc#health) and restart Dshackle if it doesn't have enough working upstreams

Validation has already been disabled for all upstream, this one from the Infura part:
```
      - id: infura
        chain: ethereum
        role: primary
        priority: 10
        options:
          disable-validation: true
          validation-interval: 60
        connection:
          ethereum:
            rpc:
              url: "https://mainnet.infura.io/v3/${INFURA_USER}"
```

Will try Health Checks, thank you.
