### ISSUE TITLE
Allowed smart contracts

### ISSUE THREAD

**Issue by splix** [emeraldpay/dshackle#23]
Configuration to setup list of addresses that can be used in `eth_call` on Ethereum.

Example config:
```yaml
authorized:

  # allows any method call
  - blockchain: ethereum
    address: 0xdac17f958d2ee523a2206206994597c13d831ec7

  # allow only call to the specified methods  
  - blockchain: ethereum
    address: 0x6b175474e89094c44da98b954eedeac495271d0f
    methods: ["0x18160ddd", "0x70a08231", "0xdd62ed3e"]
```
