### ISSUE TITLE
Sepolia support?

### ISSUE THREAD

**Issue by PDVJAM** [emeraldpay/dshackle#243]
Hey. Can dshackle work with sepolia testnet?

**Comment by splix** [comment]
@PDVJAM did you test it with Sepolia? I didn't check it out, but I guess we want Dshackle to be compatible with Sepolia

**Comment by PDVJAM** [comment]
Hey. Yes, I was able to create a separate dshackle instance and with just Ethereum configuration it works with Sepolia.
```
      - id: infura
        blockchain: ethereum
        role: secondary
        priority: 10
        options:
          disable-validation: true
          validation-interval: 60
        connection:
          ethereum:
            rpc:
              url: "https://sepolia.infura.io/v3/${INFURA_KEY}"
            ws:
              url: "wss://sepolia.infura.io/ws/v3/${INFURA_KEY}"
```
