### ISSUE TITLE
switch to fallback server

### ISSUE THREAD

**Issue by mazeboard** [emeraldpay/dshackle#251]
I am testing dshackle with a primary server that only responds with HTTP status code 429, and fallback server that uses INFURA (mainnet)

I was expecting dshackle upon receiving the HTTP status 429 from the primary server to switch to the fallback server, but dshackle returns HTTP status 200 and returns the response of the primary server instead of switching to the fallback server

The primary server is implemented using ncat command as follows:

```
while true; do {   
  echo -n -e 'HTTP/1.1 429 Too Many Requests\r\nContent-Length: 77\r\n\r\n{"jsonrpc":"2.0","id":1,"error":{"code":-32005,"message":"too many request"}}'; 
} | ncat -l 0.0.0.0 8088; done
```

and the config file dshackle.yaml is:

```
version: v1
host: 0.0.0.0 # (1)
port: 2449
tls: # (2)
  enabled: false
proxy:
  host: 0.0.0.0 # (3)
  port: 8545
  routes:
    - id: eth
      blockchain: ethereum
access-log:
  enabled: true
  filename: /tmp/access_log.jsonl
request-log:
  enabled: true
  filename: /tmp/request_log.jsonl
monitoring:
  enabled: true
  jvm: false
  extended: false
  prometheus:
    enabled: true
    bind: 0.0.0.0
    port: 8000
    path: /status/prometheus
cluster:
  upstreams: # (4)
    - id: local-eth
      blockchain: ethereum # (5)
      role: primary
      options:
         priority: 10
         disable-validation: true
      connection:
        ethereum:
          rpc: so dshackle does not use correctly the fallback server, it returns an error instead of using the fallback (edited)# (6)
            url: "http://ankbot:8088" # (7)
          #ws:
          #  url: "wss://mainnet.infura.io/ws/v3/${INFURA_USER}"
    - id: infura-eth # (9)
      blockchain: ethereum
      role: fallback
      options:
         priority: 20
         disable-validation: true
      connection:
        ethereum:
          rpc: # (6)
            #url: "https://ankbot:8088"  
            url: "https://mainnet.infura.io/v3/${INFURA_USER}" # (7)
          #ws:
          #  url: "wss://mainnet.infura.io/ws/v3/${INFURA_USER}"
```

Thanks in advance for your help
