### ISSUE TITLE
Select enabled chains for grpc upstream

### ISSUE THREAD

**Issue by splix** [emeraldpay/dshackle#37]
Currently Dshackle uses all available blockchain if connected through gRPC. Make is possible to specify list of allowed blockchain that should be used instead of all.

Use only ethereum blockchain:
```
  - id: remote-1
    chain: ethereum
    connection:
      grpc: ...
```

Use only ethereum and kovan blockchains:
```
  - id: remote-2
    chain: [ethereum, kovan]
    connection:
      grpc: ...
```
