### ISSUE TITLE
enable/disable upstream

### ISSUE THREAD

**Issue by splix** [emeraldpay/dshackle#49]
Configuration option to disable connection per upstream. With ability to use environment variables.

```
- id: some-upstream
  enabled: false
  chain: ethereum
  connection:
    ....
```
