### ISSUE TITLE
Documentation of `cluster` and Load Balancing

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#7]
I'm confused about the use of `cluster` keyword, as well as how to actually load balance between nodes. The docs only talk about a single Infura connection for the most part...

* In the README you use `cluster:` to define upstreams.
* The README states the following incorrectly (I think?):
> two upstreams, one for Ethereum Mainnet and another for Kovan Testnet (both upstreams are configured to use Infura endpoint)

The only part of that config that references kovan is
```
- chains:
  - kovan
```
But the infura connections are all `mainnet`

* Under Server Config documentation you use:
```
cluster:
  include: "upstreams.yaml"
```

* You then use this under the enable JSON section:
```
upstreams:
  config: "upstreams.yaml"
```

* Under the Upstream Config document you don't make use of the `cluster` keyword at all.

I also can't find a single example of how you actually handle load balancing

**Comment by splix** [comment]
Thank you, good points, thank you for bringing it up. Some of them are there because the project is in development yet, different parts of the doc were updated in different time, and now there is some inconsistency.

Like `upstream.config` was in a previous config, now it should be `cluster.include`.

Also it seems that it's not clear, as you pointed, that there could be many upstreams for a same blockchain, which makes actual load balancing. All the configs use single upstream config for simplicity, but I guess it's only confusing.

**Comment by MysticRyuujin** [comment]
So my goal would be primarily to have it load balance between 2 or more nodes... 

Optionally, fall back on infura.

Would this work?

```
cluster:
  upstreams:
    - id: nethermind01
      chain: ethereum
      connection:
        ethereum:
          rpc:
            url: "http://<ipaddress>:8545"
          ws:
            url: "ws://<ipaddress>:8545/ws/json-rpc"
    - id: nethermind02
      chain: ethereum
      connection:
        ethereum:
          rpc:
            url: "http://<ipaddress>:8545"
          ws:
            url: "ws://<ipaddress>:8545/ws/json-rpc"
    - id: infura-eth
      chain: ethereum
      labels:
        provider: infura
      options:
        disable-validation: true
      connection:
        ethereum:
          rpc:
            url: "https://mainnet.infura.io/v3/${INFURA_USER}"
          ws:
            url: "wss://mainnet.infura.io/ws/v3/${INFURA_USER}"
```
