### ISSUE TITLE
FR: More Selective Routes

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#75]
In the config we can create routes e.g.
```
  routes:
    - id: eth
      blockchain: ethereum
```

These routes (i.e. /eth) are then sent to the nodes as defined by their `chain: ethereum` tag.

What I'd like to be able to do is create a route (e.g. /geth) and be able to only send those requests to specific nodes.

Example:
```
  routes:
    - id: eth
      blockchain: ethereum
    - id: geth
      blockchain: ethereum
    - id: nethermind
      blockchain: ethereum

  upstreams:
    - id: geth01
      chain: ethereum
      routes:
        - eth
        - geth
...
    - id: nethermind01
      chain: ethereum
      routes:
        - eth
        - nethermind
```

This would allow all nodes to process requests to /eth and only target nodes to /whatever

I THINK you already have something like with with grpc? I know there's a labels tag, but I don't think we can use those at all with the JSON RPC? Maybe we could do something like `/eth?provider=Nethermind` if we had a lable called `provider`?

I don't particularly care in what way this would be implemented but it would be nice.
