### ISSUE TITLE
redis over TLS?

### ISSUE THREAD

**Issue by MysticRyuujin** [emeraldpay/dshackle#84]
Does dshackle support Redis connection over TLS? I can't seem to find that answer. Initial attempts don't seem to work but I'm not sure if I'm doing it right :smile: 

I'm trying to deploy an Azure Redis Cache and by default TLS is enforced. So my connection string looks like:

```
<redacted>.redis.cache.windows.net:6380,password=<redacted>,ssl=True,abortConnect=False
```

And dshackle.yaml I got:

```
cache:
  redis:
    enabled: true
    host: <redacted>.redis.cache.windows.net
    port: 6380
    password: "<redacted>"
```
Basically it hangs for a while, then throws an error, so I'm guessing it's not trying to use TLS? But I don't see a flag to enable it in the docs.

Thanks!
