### ISSUE TITLE
Empty response for eth_getLogs

### ISSUE THREAD

**Issue by SpontaneousOverthrow** [emeraldpay/dshackle#95]
Dshackle versions: master and `emeraldpay/dshackle:latest`

Dshackle config:
```
version: v1
port: 2449
tls:
  enabled: false

proxy:
  host: 0.0.0.0
  port: 8545
  routes:
    - id: mainnet
      blockchain: ethereum

cluster:
  upstreams:
        #Auto generated using ansible
    - id: mainnet-erigon-archive-node-01
      chain: ethereum
      labels:
        archive: true

      connection:
        ethereum:
          rpc:
            url: "http://10.0.10.1:38545"
          ws:
            url: "ws://10.0.10.1:38546"
```

Request to dshackle:
```
$ curl --request POST --url 127.0.0.1:8545/mainnet --header 'content-type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b"]}],"id":74}'
$
```

Request to eth-node:
```
$ curl --request POST --url http://10.0.10.1:8545 --header 'content-type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["0x000000000000000000000000a94f5374fce5edbc8e2a8697c15331677e6ebf0b"]}],"id":74}'
{"jsonrpc":"2.0","id":74,"result":[]}
```
